version: '3.4'
services:
  tests:
    image: ipscans
    build:
      context: .
      target: test
      dockerfile: Dockerfile
    container_name: ipscans-tests
    command: ["gotestsum", "--junitfile", "/tmp/test-results/unit-tests.xml"]
  db:
    image: postgres:alpine
    restart: always
    container_name: ipscans-postgres
    expose:
      - 5432
    ports:
      - ${PUBLIC_DB_PORT:-5432}:5432
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5